package routing // import "github.com/jacekk/go-rest-api-playground/internal/routing"

import (
	"fmt"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"

	_ "github.com/jacekk/go-rest-api-playground/docs" // docs is generated by Swag CLI, you have to import it.
)

func SetupRouter() *gin.Engine {
	router := gin.Default()

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.POST("/login", Login)
	router.POST("/mail/send", MailJson)
	router.POST("/validate/dics", ValidateDics)
	router.POST("/validate/user", ValidateUser)

	simple := router.Group("/simple")
	{
		simple.GET("/json", GetQuery)
		simple.GET("/plain", GetPlainText)
		simple.GET("/uno/:dos/*tres", GetParams)

		simple.POST("/json", PostJson)
		simple.POST("/xml", PostXml)
		simple.POST("/yml", PostYml)
	}
	posts := router.Group("/posts")
	{
		posts.DELETE("/:id", DeletePost)
		posts.GET("", GetPosts)
		posts.GET("/:id", GetPost)
		posts.POST("", CreatePost)
	}
	users := router.Group("/users")
	{
		users.DELETE("/:id", DeleteUser)
		users.GET("", GetUsers)
		users.GET("/:id", GetUser)
		users.GET("/:id/posts", GetUserPosts)
		users.POST("", CreateUser)
	}

	return router
}

func InitRouter(port string) {
	router := SetupRouter()
	err := router.Run(fmt.Sprintf(":%s", port))

	if err != nil {
		panic(err.Error())
	}
}
